"""runtime layer

Revision ID: 6c1f5f12e174
Revises: 0001_governance
Create Date: 2026-09-09 22:24:08.038286

🚨 `import pgvector` 는 지우지 마십시오 — autogenerate 가 Vector 컬럼을 쓴 마이그레이션을
   만들면 이 import 가 있어야 실행됩니다 (D-84 ⑪).
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector  # noqa: F401  — Vector 컬럼용. 지우지 마십시오
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "6c1f5f12e174"
down_revision: str | None = "0001_governance"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_doc",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("consent_store", sa.Boolean(), nullable=False),
        sa.Column("consent_train", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind in ('single','batch')", name="ck_work_doc_kind"),
        sa.CheckConstraint(
            "consent_store OR expires_at IS NOT NULL", name="ck_work_doc_expiry_without_consent"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_doc_expires_at"), "work_doc", ["expires_at"], unique=False)
    op.create_index(op.f("ix_work_doc_owner_id"), "work_doc", ["owner_id"], unique=False)
    op.create_index(op.f("ix_work_doc_session_id"), "work_doc", ["session_id"], unique=False)
    op.create_table(
        "batch_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("done", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state in ('pending','parsing','checking','revising','ready','failed')",
            name="ck_batch_run_state",
        ),
        sa.CheckConstraint("done <= total", name="ck_batch_run_progress"),
        sa.ForeignKeyConstraint(["doc_id"], ["work_doc.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_batch_run_doc_id"), "batch_run", ["doc_id"], unique=False)
    op.create_table(
        "copy_sentence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column("raw", sa.Text(), nullable=False),
        sa.Column("norm", sa.Text(), nullable=False),
        sa.Column("offset_map", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("external_ref", sa.String(length=120), nullable=True),
        sa.Column("image_description", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "origin in ('user','generated','batch','crawl')", name="ck_copy_sentence_origin"
        ),
        sa.ForeignKeyConstraint(["doc_id"], ["work_doc.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_copy_sentence_doc_id"), "copy_sentence", ["doc_id"], unique=False)
    op.create_table(
        "judgment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column("subject_type", sa.String(length=20), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("verdict", sa.String(length=24), nullable=False),
        sa.Column("hold_reason", sa.String(length=16), nullable=True),
        sa.Column("product_category", sa.String(length=40), nullable=True),
        sa.Column("violation_type", sa.String(length=40), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence_span", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("risk_floor", sa.Integer(), nullable=True),
        sa.Column("risk_final", sa.Integer(), nullable=True),
        sa.Column("law_version", sa.String(length=40), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("screened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("judged_by", sa.String(length=80), nullable=False),
        sa.Column(
            "judged_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "(verdict = 'hold') = (hold_reason IS NOT NULL)", name="ck_judgment_hold_reason"
        ),
        sa.CheckConstraint(
            "hold_reason IS NULL OR hold_reason in ('low_conf','gap2','cat_unknown','rd1')",
            name="ck_judgment_hold_reason_values",
        ),
        sa.CheckConstraint(
            "subject_type in ('copy_sentence','claim')", name="ck_judgment_subject_type"
        ),
        sa.CheckConstraint(
            "verdict in ('confirmed','hold','no_basis','unjudged')", name="ck_judgment_verdict"
        ),
        sa.CheckConstraint("attempt BETWEEN 0 AND 2", name="ck_judgment_attempt"),
        sa.CheckConstraint(
            "risk_final IS NULL OR risk_final BETWEEN 0 AND 4", name="ck_judgment_risk_final"
        ),
        sa.CheckConstraint(
            "risk_final IS NULL OR risk_floor IS NULL OR risk_final <= risk_floor OR evidence_span IS NOT NULL",
            name="ck_judgment_raise_needs_evidence",
        ),
        sa.CheckConstraint(
            "risk_floor IS NULL OR risk_floor BETWEEN 0 AND 4", name="ck_judgment_risk_floor"
        ),
        sa.ForeignKeyConstraint(["doc_id"], ["work_doc.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_judgment_doc_id"), "judgment", ["doc_id"], unique=False)
    op.create_index("ix_judgment_subject", "judgment", ["subject_type", "subject_id"], unique=False)
    op.create_table(
        "upload_blob",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("path", sa.String(length=300), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind in ('csv','image')", name="ck_upload_blob_kind"),
        sa.ForeignKeyConstraint(["doc_id"], ["work_doc.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_upload_blob_doc_id"), "upload_blob", ["doc_id"], unique=False)
    op.create_table(
        "slot_assignment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column("template", sa.String(length=24), nullable=False),
        sa.Column("slot", sa.String(length=24), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("sentence_id", sa.UUID(), nullable=True),
        sa.Column("image_ref", sa.String(length=200), nullable=True),
        sa.Column("unreviewed_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["doc_id"], ["work_doc.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sentence_id"], ["copy_sentence.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_slot_assignment_doc_id"), "slot_assignment", ["doc_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_slot_assignment_doc_id"), table_name="slot_assignment")
    op.drop_table("slot_assignment")
    op.drop_index(op.f("ix_upload_blob_doc_id"), table_name="upload_blob")
    op.drop_table("upload_blob")
    op.drop_index("ix_judgment_subject", table_name="judgment")
    op.drop_index(op.f("ix_judgment_doc_id"), table_name="judgment")
    op.drop_table("judgment")
    op.drop_index(op.f("ix_copy_sentence_doc_id"), table_name="copy_sentence")
    op.drop_table("copy_sentence")
    op.drop_index(op.f("ix_batch_run_doc_id"), table_name="batch_run")
    op.drop_table("batch_run")
    op.drop_index(op.f("ix_work_doc_session_id"), table_name="work_doc")
    op.drop_index(op.f("ix_work_doc_owner_id"), table_name="work_doc")
    op.drop_index(op.f("ix_work_doc_expires_at"), table_name="work_doc")
    op.drop_table("work_doc")
    # ### end Alembic commands ###
